### ISSUE TITLE
Cannot redeclare include_field_types_wp_wysiwyg() 

### ISSUE THREAD

**Issue by derkoosterveld** [elliotcondon/acf-wordpress-wysiwyg-field#16]
Hi Elliot again ;-),

I'm getting this error when I'm including the file in my functions.php:

```
Fatal error: Cannot redeclare include_field_types_wp_wysiwyg() (previously declared in /Users/derkoosterveld/Documents/svn/uit_zeilen/wp-content/plugins/acf-wordpress-wysiwyg-field-master/acf-wp_wysiwyg.php:21) in /Users/derkoosterveld/Documents/svn/uit_zeilen/wp-content/themes/uit_zeilen/inc/acf-wordpress-wysiwyg-field-master/acf-wp_wysiwyg.php on line 25
```

Do you know why?

Thanks!

**Comment by elliotcondon** [comment]
Hi Derk,

Your error shows that your theme already includes this class, and you are trying to install a plugin with the same class.

Simply deactivate the plugin, there is no need to to have 2 instances of the WYSYWG field

**Comment by derkoosterveld** [comment]
Allright, I deleted that and have the plug-in activated but don't see the nice tabs I expected with the plug-in.

<img width="1187" alt="schermafbeelding 2016-01-11 om 08 05 19" src="https://cloud.githubusercontent.com/assets/1818241/12228334/15404270-b83a-11e5-9285-641b481c4585.png">

**Comment by elliotcondon** [comment]
Hi @derkoosterveld 

Your screenshot is showing a normal ACF v4 WYSIWYG field, not the WP WYSIWYG field.
Are you sure you have selected the correct field type?
You need to edit the field, and change the type from WYSIWYG to WP WYSIWYG (they are 2 different fields)
