### ISSUE TITLE
WYSIWYG not displaying correctly for Taxonomies

### ISSUE THREAD

**Issue by olospo** [elliotcondon/acf-wordpress-wysiwyg-field#7]
If I use the field type "Wysiwyg Editor" you can only see the visual area (no tab for text) and with "WP WYSIWYG" you can only edit in the text view (visual tab button doesn't work) 

This is only when editing content for Categories. The same field types work fine in Posts/Pages.

![screen shot 2013-12-04 at 11 30 40](https://f.cloud.github.com/assets/990838/1672736/0a75b0c4-5cd8-11e3-906c-0a88836f1d7f.png)

**Comment by dsovino** [comment]
Same here, on WP 4.2, ACF 4.4.1 and ACF WP WYSIWYG 1.0.2

**Comment by elliotcondon** [comment]
Hi guys

Looks like a JS error on the page is preventing the tinymce from loading.
Can you please check your console log and report any JS errors?

Thanks
E

**Comment by dsovino** [comment]
No JS errors on Console. I don´t see any 404s as well either...

**Comment by elliotcondon** [comment]
Hi guys

Thanks for the bug report.

I've done some testing and found that this is a frustrating limitation of this field.
It is the same issue that prevents it working as a sub field (can't be appended via JS)

Please note that ACF PRO and ACF5 (soon to be released) have a much smarter WYSIWYG field which uses the native WP editor with some smart JS to allow it to work within the repeater field and category pages!

Sorry that I don't have a solution for this issue, but please await either ACF5 or upgrade to ACF PRO

Cheers
E
